/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package mvc.controller;

import jakarta.servlet.ServletContextListener; 
import jakarta.servlet.ServletContextEvent;
import jakarta.servlet.annotation.WebListener;

import mvc.model.Model;
import mvc.model.DBManager;

/**
 * Manages the context of the application.
 * Instantiates the Model class when the app is created, so that it can be later accessed by the servlets.
 * 
 * @author Milosz Liniewiecki
 * @version 1.0
 */
@WebListener // We need that so that the notification about the lifecycle events of the servlets are received
public class AppContextListener implements ServletContextListener {
    
    /**
     * Instance of the Model from MVC pattern.
     * It can handle encoding / decoding and validation of strings.
     * It also stores history of oeprations.
     */
    private Model model;
    
    /**
     * Takes care of communication with the database.
     * Creates the tables, persists objects in them and 
     */
    DBManager dbManager;
    
    /**
     * Default constructor of the AppContextListener is empty.
     */
    public AppContextListener(){

    }
    
    /**
     * Invoked when the servlets of the application are created.
     * Sets the {@link #model} as an attribute of every servlet context.
     * 
     * @param sec Event generated by the app when it is created.
     */
    @Override
    public void contextInitialized(ServletContextEvent sec){

        // Initialize the model 
        model = new Model();
        model.clearKey();
        model.generateDefaultKey();
        
        String puName = sec.getServletContext().getInitParameter("persistenceUnitName");
        
        // Init the Database Manager 
        dbManager = new DBManager(puName);
        
        // Set the model for sevlets context
        sec.getServletContext().setAttribute("model", model);
        sec.getServletContext().setAttribute("dbManager", dbManager);
    }
}
